#title必须设置和github上该repository的name一致，如果该repository name为"用户名.github.io"，则不需要填。
title: SimpleTheme

#author设置为github用户名
author: lcfu1

description: SimpleTheme

#把下面这个theme注释掉
#theme: jekyll-theme-cayman
