#title必须设置和github上该repository的name一致。
title: SimpleTheme

#author设置为github用户名
author: lcfu1

#记得把下面这个theme注释掉
#theme: jekyll-theme-cayman

#Application ID
id: d6f5df1e30903a0a49634f3ac9c96ecf

#REST API Key
key: 29bc5d837e8c6054da46fde3ddfce1c8
